# Ejercicio 5: Espacio Vectorial
---
- **Nombre**: Michael Enríquez
- **Fecha**: 13 de mayo, 2026
---
## Objetivo de la práctica
- Implementar un Sistema de Recuperación de Información completo, desde la lectura del corpus hasta la recuperación de resultados.

## Parte 0: Carga del Corpus

Vamos a utilizar la API de Kaggle para acceder al dataset _Wikipedia Text Corpus for NLP and LLM Projects_

El corpus está disponible desde este [link](https://www.kaggle.com/datasets/gzdekzlkaya/wikipedia-text-corpus-for-nlp-and-llm-projects?utm_source=chatgpt.com)

### Actividad

1. Carga el corpus
2. Realiza las etapas de preprocesamiento sobre el corpus

In [13]:
import os
import pandas as pd
import kagglehub

# Descargar dataset
dataset_path = kagglehub.dataset_download(
    "gzdekzlkaya/wikipedia-text-corpus-for-nlp-and-llm-projects"
)

# Buscar el archivo CSV
csv_file = [f for f in os.listdir(dataset_path) if f.endswith(".csv")][0]
csv_path = os.path.join(dataset_path, csv_file)

# Cargar dataset
df = pd.read_csv(csv_path)

# Convertir a corpus de documentos
documents = df['text'].astype(str).tolist()

# IDs de documentos
doc_ids = [f"doc_{i}" for i in range(len(documents))]

print(f"\nDocumentos cargados: {len(documents)}")

Documentos cargados: 10859

Primer documento:
Anovo

Anovo (formerly A Novo) is a computer services company based in Beauvais, France. It was founded in 1987, went public in 1999, and is currently a member of the CAC Small.

It won in the category 'Service and Repair' of the Mobile News Awards four years in a row, from 2007 to 2010.

As of November 2017, they have a score of 1.6 out of 10 on the TrustPilot ratings site, with 86% of reviewers giving the company the lowest possible rating.

In [15]:
# Crear Dataframe 
df = pd.DataFrame({'document': documents, 'doc_id': doc_ids})
df

                                                document     doc_id
0      Anovo\n\nAnovo (formerly A Novo) is a computer...      doc_0
1      Battery indicator\n\nA battery indicator (also...      doc_1
2      Bob Pease\n\nRobert Allen Pease (August 22, 19...      doc_2
3      CAVNET\n\nCAVNET was a secure military forum w...      doc_3
4      CLidar\n\nThe CLidar is a scientific instrumen...      doc_4
...                                                  ...        ...
10854  Soundcast\n\nSoundcast LLC is a privately fund...  doc_10854
10855  Spectrum analyzer\n\nA spectrum analyzer measu...  doc_10855
10856  Telepresence technology\n\nTelepresence techno...  doc_10856
10857  Trans-Pacific Profiler Network\n\nThe Trans-Pa...  doc_10857
10858  Transfer case\n\nA transfer case is a part of ...  doc_10858

[10859 rows x 2 columns]

In [18]:
import nltk
nltk.download('punkt')
nltk.download('stopwords')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\LabP5E004\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\LabP5E004\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [19]:
# Limpiar datos:
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import PorterStemmer
import re

stemmer = PorterStemmer()
stop_words = set(stopwords.words('english'))

def limpiar_texto(text):
    texto_lower = text.lower()
    texto_limpio = re.sub(r'[^a-zA-Z0-9\s]', '', texto_lower)
    tokens = word_tokenize(texto_limpio)

    tokens = [t for t in tokens if t not in stop_words]
    stems = [stemmer.stem(p) for p in tokens]

    return ' '.join(stems)

df['prep'] = df['document'].apply(limpiar_texto)
df

,document,doc_id,prep
0,Anovo\n\nAnovo (formerly A Novo) is a computer...,doc_0,anovo anovo formerli novo comput servic compan...
1,Battery indicator\n\nA battery indicator (also...,doc_1,batteri indic batteri indic also known batteri...
2,"Bob Pease\n\nRobert Allen Pease (August 22, 19...",doc_2,bob peas robert allen peas august 22 1940 june...
3,CAVNET\n\nCAVNET was a secure military forum w...,doc_3,cavnet cavnet secur militari forum becam oper ...
4,CLidar\n\nThe CLidar is a scientific instrumen...,doc_4,clidar clidar scientif instrument use measur p...
...,...,...,...
10854,Soundcast\n\nSoundcast LLC is a privately fund...,doc_10854,soundcast soundcast llc privat fund compani cr...
10855,Spectrum analyzer\n\nA spectrum analyzer measu...,doc_10855,spectrum analyz spectrum analyz measur magnitu...
10856,Telepresence technology\n\nTelepresence techno...,doc_10856,telepres technolog telepres technolog term use...
10857,Trans-Pacific Profiler Network\n\nThe Trans-Pa...,doc_10857,transpacif profil network transpacif profil ne...
10858,Transfer case\n\nA transfer case is a part of ...,doc_10858,transfer case transfer case part drivetrain fo...

## Parte 1: Recuperación con TF-IDF

### Actividad:
3. Obtén la representación vectorial de los documentos utilizando el modelo TF-IDF
4. A partir de un conjunto de 10 queries, verifica la recuperación del sistema

In [32]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np

# Crear vectorizador TF-IDF
vectorizer = TfidfVectorizer(max_features=5000, min_df=2, max_df=0.8)

# Transformar documentos preprocesados
tfidf_matrix = vectorizer.fit_transform(df['prep'])

# Conjunto de 10 queries de prueba
queries = [
    "science and technology",
    "history of ancient civilizations",
    "literature and art",
    "mathematics and physics",
    "biological systems",
    "geography and culture",
    "political systems",
    "philosophy and ethics",
    "economics and trade",
    "nature and environment"
]

# Ejecutar búsquedas

print("RESULTADOS DE BÚSQUEDA TF-IDF\n")

for i, query in enumerate(queries, 1):
    # Preprocesar query
    query_prep = limpiar_texto(query)
    
    # Transformar query
    query_tfidf = vectorizer.transform([query_prep])
    
    # Calcular similitud
    df['dist'] = cosine_similarity(tfidf_matrix, query_tfidf).flatten()
    
    # Ordenar por similitud descendente
    results = df.sort_values(by='dist', ascending=False).head(3)
    
    # Mostrar resultados
    print(f"\nQuery {i}: '{query}'")
    print(f"   Preprocesado: '{query_prep}'\n")
    
    for idx, (_, row) in enumerate(results.iterrows(), 1):
        if row['dist'] > 0:
            print(f"  {idx}. [{row['doc_id']}] Similitud: {row['dist']:.4f}")
            print(f"     {row['document'][:100]}...")

df

RESULTADOS DE BÚSQUEDA TF-IDF


Query 1: 'science and technology'
   Preprocesado: 'scienc technolog'

  1. [doc_618] Similitud: 0.6559
     Ministry of Science and Technology (Bangladesh)

The Ministry of Science and Technology (; "BijÃ±Än...
  2. [doc_3842] Similitud: 0.6515
     Ministry of Science and Technology (China)

The Ministry of Science and Technology (MOST) of the Peo...
  3. [doc_1317] Similitud: 0.6188
     Ministry of Science and Technology (Taiwan)

The Ministry of Science and Technology (MOST; ) is the ...

Query 2: 'history of ancient civilizations'
   Preprocesado: 'histori ancient civil'

  1. [doc_2186] Similitud: 0.3580
     Civil engineer

A civil engineer is a person who practices civil engineering â€“ the application of ...
  2. [doc_2332] Similitud: 0.3335
     Civil engineering database

The Civil Engineering Database (CEDB) was created in 1994, and is mainta...
  3. [doc_1884] Similitud: 0.2999
     Advanced Technician in Aviation non civil servant

In France, the training of the Technicien supÃ©ri...

Query 3: 'literature and art'
   Preprocesado: 'literatur art'

  1. [doc_5475] Similitud: 0.4907
     Artes Mechanicae

Artes Mechanicae or mechanical arts, are a medieval concept of ordered practices o...
  2. [doc_2901] Similitud: 0.4550
     Roy Ascott

Roy Ascott (born 26 October 1934) is a British artist, who works with cybernetics and te...
  3. [doc_9397] Similitud: 0.4526
     Grey literature

Grey literature (or gray literature) are materials and research produced by organiz...

Query 4: 'mathematics and physics'
   Preprocesado: 'mathemat physic'

  1. [doc_1734] Similitud: 0.5248
     Alexander Bogomolny

Alexander Bogomolny (January 4, 1948July 7, 2018) was an Israeli American mathe...
  2. [doc_8266] Similitud: 0.3516
     Rafail Krichevskii

Rafail Evseevich Krichevskii (Ğ Ğ°Ñ„Ğ°Ğ¸Ğ» Ğ•Ğ²ÑĞµĞµĞ²Ğ¸Ñ‡ ĞšÑ€Ğ¸Ñ‡ĞµĞ²ÑĞºĞ¸Ğ¹...
  3. [doc_3757] Similitud: 0.3181
     Alfred Inselberg

Alfred Inselberg is an American-Israeli mathematician and computer scientist based...

Query 5: 'biological systems'
   Preprocesado: 'biolog system'

  1. [doc_5592] Similitud: 0.5133
     International Organization for Biological Control

The International Organization for Biological and...
  2. [doc_8835] Similitud: 0.4843
     Biological Resource Center

A Biological Resource Centre (BRC) is considered to be one of the key el...
  3. [doc_598] Similitud: 0.4368
     Bernhard Hassenstein

Bernhard Hassenstein (31 May 1922 â€“ 16 April 2016) was a German biologist an...

Query 6: 'geography and culture'
   Preprocesado: 'geographi cultur'

  1. [doc_6032] Similitud: 0.7336
     Emiran

Emiran culture was a culture that existed in the Levant (Syria, Lebanon, Israel, Palestine) ...
  2. [doc_7355] Similitud: 0.6958
     Cultural industry

According to international organizations such as UNESCO and the General Agreement...
  3. [doc_2157] Similitud: 0.4763
     Leister

A leister is a type of spear used for fishing.

Leisters have been used by hunter-gatherer ...

Query 7: 'political systems'
   Preprocesado: 'polit system'

  1. [doc_4823] Similitud: 0.2849
     Minister of Energy, Science, Technology, Environment and Climate Change (Malaysia)

The current Mala...
  2. [doc_6950] Similitud: 0.2619
     Ultra-large-scale systems

Ultra-large-scale system (ULSS) is a term used in fields including Comput...
  3. [doc_174] Similitud: 0.1989
     Information system

Information systems (IS) are formal, sociotechnical, organizational systems desi...

Query 8: 'philosophy and ethics'
   Preprocesado: 'philosophi ethic'

  1. [doc_9852] Similitud: 0.4974
     Philosophy of computer science

The philosophy of computer science is concerned with the philosophic...
  2. [doc_8229] Similitud: 0.3927
     TechnÃ©: Research in Philosophy and Technology

TechnÃ©: Research in Philosophy and Technology is a ...
  3. [doc_6579] Similitud: 0.3601
     Ernesto Priani

Ernesto Priani (9 May 1962 Mexico City) is a philosopher, professor, digital humanis...

Query 9: 'economics and trade'
   Preprocesado: 'econom trade'

  1. [doc_2570] Similitud: 0.5277
     Automated trading system

An automated trading system (ATS), also referred to as algorithmic trading...
  2. [doc_1004] Similitud: 0.5177
     Electronic trading

Electronic or scripless trading, sometimes called e-trading or paperless trading...
  3. [doc_108] Similitud: 0.4249
     Day trading software

Day trading software is computer software intended to facilitate day trading o...

Query 10: 'nature and environment'
   Preprocesado: 'natur environ'

  1. [doc_8911] Similitud: 0.3313
     Ministry of Environment and Energy (Greece)

The Ministry of Environment and Energy () is a governme...
  2. [doc_5440] Similitud: 0.3121
     Energy and environmental engineering

Energy and environmental engineering is a branch of engineerin...
  3. [doc_1809] Similitud: 0.3057
     Intelligent environment

Intelligent Environments (IE) are spaces with embedded systems and informat...

,document,doc_id,prep,dist
0,Anovo\n\nAnovo (formerly A Novo) is a computer...,doc_0,anovo anovo formerli novo comput servic compan...,0.000000
1,Battery indicator\n\nA battery indicator (also...,doc_1,batteri indic batteri indic also known batteri...,0.000000
2,"Bob Pease\n\nRobert Allen Pease (August 22, 19...",doc_2,bob peas robert allen peas august 22 1940 june...,0.000000
3,CAVNET\n\nCAVNET was a secure military forum w...,doc_3,cavnet cavnet secur militari forum becam oper ...,0.000000
4,CLidar\n\nThe CLidar is a scientific instrumen...,doc_4,clidar clidar scientif instrument use measur p...,0.000000
...,...,...,...,...
10854,Soundcast\n\nSoundcast LLC is a privately fund...,doc_10854,soundcast soundcast llc privat fund compani cr...,0.000000
10855,Spectrum analyzer\n\nA spectrum analyzer measu...,doc_10855,spectrum analyz spectrum analyz measur magnitu...,0.006694
10856,Telepresence technology\n\nTelepresence techno...,doc_10856,telepres technolog telepres technolog term use...,0.078498
10857,Trans-Pacific Profiler Network\n\nThe Trans-Pa...,doc_10857,transpacif profil network transpacif profil ne...,0.000000
10858,Transfer case\n\nA transfer case is a part of ...,doc_10858,transfer case transfer case part drivetrain fo...,0.000000

## Parte 2: Recuperación con BM25

### Actividad:
5. Implementa un sistema de recuperación usando el modelo BM25.
6. Para el mismo conjunto de 10 queries, verifica la recuperación del sistema

In [33]:
from rank_bm25 import BM25Okapi

# Tokenizar documentos preprocesados (ya están limpios)
tokenized_docs = [doc.split() for doc in df['prep']]

# Crear modelo BM25
bm25 = BM25Okapi(tokenized_docs)

print(f"Corpus BM25 creado: {len(tokenized_docs)} documentos")

# Ejecutar búsquedas
print("\nRESULTADOS DE BÚSQUEDA BM25")

for i, query in enumerate(queries, 1):
    # Preprocesar query
    query_prep = limpiar_texto(query)
    query_tokens = query_prep.split()
    
    # Calcular scores BM25
    scores = bm25.get_scores(query_tokens)
    df['score'] = scores
    
    # Ordenar por score descendente
    results = df.sort_values(by='score', ascending=False).head(3)
    
    # Mostrar resultados
    print(f"\nQuery {i}: '{query}'")
    print(f"   Preprocesado: '{query_prep}'")
    print("-" * 80)
    
    for idx, (_, row) in enumerate(results.iterrows(), 1):
        if row['dist'] > 0:
            print(f"  {idx}. [{row['doc_id']}] Score BM25: {row['dist']:.4f}")
            print(f"     {row['document'][:100]}...")

df

Corpus BM25 creado: 10859 documentos

RESULTADOS DE BÚSQUEDA BM25

Query 1: 'science and technology'
   Preprocesado: 'scienc technolog'
--------------------------------------------------------------------------------

Query 2: 'history of ancient civilizations'
   Preprocesado: 'histori ancient civil'
--------------------------------------------------------------------------------
  3. [doc_3359] Score BM25: 0.0294
     Ancient Egyptian technology

Ancient Egyptian technology describes devices and technologies invented...

Query 3: 'literature and art'
   Preprocesado: 'literatur art'
--------------------------------------------------------------------------------

Query 4: 'mathematics and physics'
   Preprocesado: 'mathemat physic'
--------------------------------------------------------------------------------
  2. [doc_7027] Score BM25: 0.0187
     Louis Kauffman

Louis Hirsch Kauffman (born February 3, 1945) is an American mathematician, topologi...

Query 5: 'biological systems'
   Preprocesado: 'biolog system'
--------------------------------------------------------------------------------
  1. [doc_5592] Score BM25: 0.0450
     International Organization for Biological Control

The International Organization for Biological and...
  3. [doc_1855] Score BM25: 0.0105
     Integrated nanoliter system

The integrated nanoliter system is a measuring, separating, and mixing ...

Query 6: 'geography and culture'
   Preprocesado: 'geographi cultur'
--------------------------------------------------------------------------------

Query 7: 'political systems'
   Preprocesado: 'polit system'
--------------------------------------------------------------------------------
  1. [doc_4823] Score BM25: 0.0983
     Minister of Energy, Science, Technology, Environment and Climate Change (Malaysia)

The current Mala...

Query 8: 'philosophy and ethics'
   Preprocesado: 'philosophi ethic'
--------------------------------------------------------------------------------
  2. [doc_3789] Score BM25: 0.0573
     Philosophy of engineering

The philosophy of engineering is an emerging discipline that considers wh...

Query 9: 'economics and trade'
   Preprocesado: 'econom trade'
--------------------------------------------------------------------------------
  2. [doc_5738] Score BM25: 0.0237
     Global waste trade

The global waste trade is the international trade of waste between countries for...
  3. [doc_6354] Score BM25: 0.0053
     Sustainable coffee

Sustainable coffee is coffee that is grown and marketed for its sustainability. ...

Query 10: 'nature and environment'
   Preprocesado: 'natur environ'
--------------------------------------------------------------------------------
  1. [doc_1349] Score BM25: 0.2074
     Federal Ministry of the Environment, Nature Conservation and Nuclear Safety

The Federal Minister fo...
  2. [doc_7140] Score BM25: 0.2121
     Simulate Loam Substrate

Simulate Loam Substrate, or mechanism-based Loam Substrate() is an ecologic...
  3. [doc_6290] Score BM25: 0.2066
     National Centre for Earth Observation

The National Centre for Earth Observation (NCEO) is part of t...

,document,doc_id,prep,dist,score
0,Anovo\n\nAnovo (formerly A Novo) is a computer...,doc_0,anovo anovo formerli novo comput servic compan...,0.000000,0.000000
1,Battery indicator\n\nA battery indicator (also...,doc_1,batteri indic batteri indic also known batteri...,0.000000,0.000000
2,"Bob Pease\n\nRobert Allen Pease (August 22, 19...",doc_2,bob peas robert allen peas august 22 1940 june...,0.000000,0.000000
3,CAVNET\n\nCAVNET was a secure military forum w...,doc_3,cavnet cavnet secur militari forum becam oper ...,0.000000,0.000000
4,CLidar\n\nThe CLidar is a scientific instrumen...,doc_4,clidar clidar scientif instrument use measur p...,0.000000,0.000000
...,...,...,...,...,...
10854,Soundcast\n\nSoundcast LLC is a privately fund...,doc_10854,soundcast soundcast llc privat fund compani cr...,0.000000,0.000000
10855,Spectrum analyzer\n\nA spectrum analyzer measu...,doc_10855,spectrum analyz spectrum analyz measur magnitu...,0.006694,1.656911
10856,Telepresence technology\n\nTelepresence techno...,doc_10856,telepres technolog telepres technolog term use...,0.078498,3.143713
10857,Trans-Pacific Profiler Network\n\nThe Trans-Pa...,doc_10857,transpacif profil network transpacif profil ne...,0.000000,0.000000
10858,Transfer case\n\nA transfer case is a part of ...,doc_10858,transfer case transfer case part drivetrain fo...,0.000000,0.000000

## Parte 3: Comparación de resultados

### Actividad:
7. Verifica cuáles documentos son recuperados (y en qué orden) por cada modelo de recuperación

In [36]:
import pandas as pd

# Almacenar resultados de ambos modelos
results_comparison = []

print("COMPARACIÓN TF-IDF vs BM25")

for i, query in enumerate(queries, 1):
    # Preprocesar query
    query_prep = limpiar_texto(query)
    query_tokens = query_prep.split()
    
    # ========== TF-IDF ==========
    query_tfidf = vectorizer.transform([query_prep])
    df['tfidf_score'] = cosine_similarity(tfidf_matrix, query_tfidf).flatten()
    tfidf_results = df.sort_values(by='tfidf_score', ascending=False).head(5)
    
    # ========== BM25 ==========
    scores = bm25.get_scores(query_tokens)
    df['bm25_score'] = scores
    bm25_results = df.sort_values(by='bm25_score', ascending=False).head(5)
    
    # Extraer doc_ids para comparación
    tfidf_docs = tfidf_results['doc_id'].values
    bm25_docs = bm25_results['doc_id'].values
    
    # Calcular coincidencias
    coincidencias = set(tfidf_docs) & set(bm25_docs)
    
    # Mostrar resultados
    print(f"\nQuery {i}: '{query}'")
    print(f"   Preprocesado: '{query_prep}'\n")
    
    # TF-IDF Top 5
    print("\n   TF-IDF Top 5:")
    for rank, (_, row) in enumerate(tfidf_results.iterrows(), 1):
        if row['tfidf_score'] > 0:
            print(f"    {rank}. {row['doc_id']:<10} Score: {row['tfidf_score']:.4f}")
    
    # BM25 Top 5
    print("\n   BM25 Top 5:")
    for rank, (_, row) in enumerate(bm25_results.iterrows(), 1):
        if row['bm25_score'] > 0:
            print(f"    {rank}. {row['doc_id']:<10} Score: {row['bm25_score']:.4f}")
    
    # Análisis de coincidencias
    print(f"\n\tAnálisis: {len(coincidencias)}/5 documentos coinciden")
    if coincidencias:
        print(f"\tDocumentos en común: {', '.join(sorted(coincidencias))}")
    
    # Guardar resultados para análisis posterior
    results_comparison.append({
        'query': query,
        'tfidf': tfidf_docs[0] if len(tfidf_docs) > 0 else None,
        'bm25': bm25_docs[0] if len(bm25_docs) > 0 else None,
        'tfidf_docs': list(tfidf_docs),
        'bm25_docs': list(bm25_docs),
        'coincidencias': len(coincidencias)
    })

# Crear DataFrame de comparación
comp_df = pd.DataFrame(results_comparison)

# Resumen global

print("\nRESUMEN GLOBAL")
print(f"\nTotal de queries: {len(queries)}")
print(f"Top 1 coincidencias: {(comp_df['tfidf'] == comp_df['bm25']).sum()}/10")
print(f"Promedio de docs coincidentes en Top 5: {comp_df['coincidencias'].mean():.2f}/5")
print(f"\nDistribución de coincidencias:")
print(comp_df['coincidencias'].value_counts().sort_index(ascending=False))

# Mostrar tabla de comparación
print("\nTABLA RESUMEN")
display(comp_df[['query', 'tfidf', 'bm25', 'coincidencias']])

COMPARACIÓN TF-IDF vs BM25

Query 1: 'science and technology'
   Preprocesado: 'scienc technolog'


   TF-IDF Top 5:
    1. doc_618    Score: 0.6559
    2. doc_3842   Score: 0.6515
    3. doc_1317   Score: 0.6188
    4. doc_6377   Score: 0.5869
    5. doc_8563   Score: 0.5470

   BM25 Top 5:
    1. doc_5501   Score: 6.0734
    2. doc_1317   Score: 5.9769
    3. doc_6377   Score: 5.9754
    4. doc_5493   Score: 5.9191
    5. doc_7921   Score: 5.8937

	Análisis: 2/5 documentos coinciden
	Documentos en común: doc_1317, doc_6377

Query 2: 'history of ancient civilizations'
   Preprocesado: 'histori ancient civil'


   TF-IDF Top 5:
    1. doc_2186   Score: 0.3580
    2. doc_2332   Score: 0.3335
    3. doc_1884   Score: 0.2999
    4. doc_8828   Score: 0.2986
    5. doc_340    Score: 0.2859

   BM25 Top 5:
    1. doc_8776   Score: 15.2221
    2. doc_4265   Score: 14.2552
    3. doc_3359   Score: 14.0373
    4. doc_8901   Score: 12.9844
    5. doc_2854   Score: 12.6198

	Análisis: 0/5 documentos coinciden

Query 3: 'literature and art'
   Preprocesado: 'literatur art'


   TF-IDF Top 5:
    1. doc_5475   Score: 0.4907
    2. doc_2901   Score: 0.4550
    3. doc_9397   Score: 0.4526
    4. doc_7052   Score: 0.3814
    5. doc_3752   Score: 0.3136

   BM25 Top 5:
    1. doc_9207   Score: 11.2847
    2. doc_9783   Score: 10.6715
    3. doc_2285   Score: 10.1428
    4. doc_2403   Score: 10.0881
    5. doc_3789   Score: 9.6493

	Análisis: 0/5 documentos coinciden

Query 4: 'mathematics and physics'
   Preprocesado: 'mathemat physic'


   TF-IDF Top 5:
    1. doc_1734   Score: 0.5248
    2. doc_8266   Score: 0.3516
    3. doc_3757   Score: 0.3181
    4. doc_5651   Score: 0.3102
    5. doc_436    Score: 0.3061

   BM25 Top 5:
    1. doc_3757   Score: 10.2004
    2. doc_7027   Score: 10.1921
    3. doc_8266   Score: 9.9077
    4. doc_9712   Score: 9.2254
    5. doc_10757  Score: 9.1807

	Análisis: 2/5 documentos coinciden
	Documentos en común: doc_3757, doc_8266

Query 5: 'biological systems'
   Preprocesado: 'biolog system'


   TF-IDF Top 5:
    1. doc_5592   Score: 0.5133
    2. doc_8835   Score: 0.4843
    3. doc_598    Score: 0.4368
    4. doc_4682   Score: 0.4247
    5. doc_9953   Score: 0.4101

   BM25 Top 5:
    1. doc_5592   Score: 7.6234
    2. doc_8835   Score: 7.6032
    3. doc_1855   Score: 7.5529
    4. doc_8487   Score: 7.4844
    5. doc_7595   Score: 7.4839

	Análisis: 2/5 documentos coinciden
	Documentos en común: doc_5592, doc_8835

Query 6: 'geography and culture'
   Preprocesado: 'geographi cultur'


   TF-IDF Top 5:
    1. doc_6032   Score: 0.7336
    2. doc_7355   Score: 0.6958
    3. doc_2157   Score: 0.4763
    4. doc_2451   Score: 0.4708
    5. doc_5036   Score: 0.3887

   BM25 Top 5:
    1. doc_10074  Score: 11.9091
    2. doc_5346   Score: 11.3670
    3. doc_8934   Score: 10.7541
    4. doc_4680   Score: 10.5870
    5. doc_6825   Score: 10.1599

	Análisis: 0/5 documentos coinciden

Query 7: 'political systems'
   Preprocesado: 'polit system'


   TF-IDF Top 5:
    1. doc_4823   Score: 0.2849
    2. doc_6950   Score: 0.2619
    3. doc_174    Score: 0.1989
    4. doc_7336   Score: 0.1968
    5. doc_3313   Score: 0.1955

   BM25 Top 5:
    1. doc_4823   Score: 7.6651
    2. doc_8598   Score: 6.9767
    3. doc_3313   Score: 6.6794
    4. doc_8513   Score: 6.6701
    5. doc_3066   Score: 6.6611

	Análisis: 2/5 documentos coinciden
	Documentos en común: doc_3313, doc_4823

Query 8: 'philosophy and ethics'
   Preprocesado: 'philosophi ethic'


   TF-IDF Top 5:
    1. doc_9852   Score: 0.4974
    2. doc_8229   Score: 0.3927
    3. doc_6579   Score: 0.3601
    4. doc_2793   Score: 0.3381
    5. doc_3789   Score: 0.2069

   BM25 Top 5:
    1. doc_6579   Score: 16.3631
    2. doc_3789   Score: 15.4147
    3. doc_2793   Score: 14.0168
    4. doc_4360   Score: 12.0769
    5. doc_1360   Score: 11.9859

	Análisis: 3/5 documentos coinciden
	Documentos en común: doc_2793, doc_3789, doc_6579

Query 9: 'economics and trade'
   Preprocesado: 'econom trade'


   TF-IDF Top 5:
    1. doc_2570   Score: 0.5277
    2. doc_1004   Score: 0.5177
    3. doc_108    Score: 0.4249
    4. doc_3301   Score: 0.3923
    5. doc_1116   Score: 0.3686

   BM25 Top 5:
    1. doc_4910   Score: 10.7395
    2. doc_5738   Score: 10.1979
    3. doc_6354   Score: 9.3413
    4. doc_2154   Score: 8.9787
    5. doc_7402   Score: 8.9590

	Análisis: 0/5 documentos coinciden

Query 10: 'nature and environment'
   Preprocesado: 'natur environ'


   TF-IDF Top 5:
    1. doc_8911   Score: 0.3313
    2. doc_5440   Score: 0.3121
    3. doc_1809   Score: 0.3057
    4. doc_4468   Score: 0.2665
    5. doc_1513   Score: 0.2438

   BM25 Top 5:
    1. doc_1349   Score: 7.5913
    2. doc_7140   Score: 7.3877
    3. doc_6290   Score: 7.1736
    4. doc_557    Score: 6.9372
    5. doc_7691   Score: 6.7697

	Análisis: 0/5 documentos coinciden

RESUMEN GLOBAL

Total de queries: 10
Top 1 coincidencias: 2/10
Promedio de docs coincidentes en Top 5: 1.10/5

Distribución de coincidencias:
coincidencias
3    1
2    4
0    5
Name: count, dtype: int64

TABLA RESUMEN

                              query     tfidf       bm25  coincidencias
0            science and technology   doc_618   doc_5501              2
1  history of ancient civilizations  doc_2186   doc_8776              0
2                literature and art  doc_5475   doc_9207              0
3           mathematics and physics  doc_1734   doc_3757              2
4                biological systems  doc_5592   doc_5592              2
5             geography and culture  doc_6032  doc_10074              0
6                 political systems  doc_4823   doc_4823              2
7             philosophy and ethics  doc_9852   doc_6579              3
8               economics and trade  doc_2570   doc_4910              0
9            nature and environment  doc_8911   doc_1349              0